WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
TILE_SIZE = 32


PACMAN_TEXTURE = "img/pacman.png"
PACMAN_ROTATION_ANGLE = 90
PACMAN_MOVE_SPEED = 1

GHOST_TEXTURE = "img/ghost.png"
GHOST_ROTATION_ANGLE = 0
GHOST_MOVE_SPEED = 1

WALL_TEXTURE = "img/wall.png"

COIN_TEXTURE = "img/coin.png"


