WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
TILE_SIZE = 32

COIN_DIAMETER = TILE_SIZE//3
COIN_COLOR = (197, 129, 0)

PACMAN_TEXTURE = "img/pacman.png"
PACMAN_ROTATION_ANGLE = 90
PACMAN_MOVE_SPEED = 3

GHOST_TEXTURE = "img/ghost.png"
GHOST_ROTATION_ANGLE = 0
GHOST_MOVE_SPEED = 2

WALL_COLOR = (0,0,225)
