WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
TILE_SIZE = 32
MAZE_CYCLE_GENERATION = 15


PACMAN_TEXTURE = "img/pacman.png"
PACMAN_ROTATION_ANGLE = 90
PACMAN_MOVE_SPEED = 2

GHOST_TEXTURE = "img/ghost.png"
GHOST_ROTATION_ANGLE = 0
GHOST_MOVE_SPEED = 2
GHOST_DELTA_TIME = 4

WALL_TEXTURE = "img/wall.png"

COIN_TEXTURE = "img/coin.png"


APPLE_TEXTURE = "img/apple.png"



